# Generated by Django 3.1.3 on 2020-12-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=32, null=True)),
                ('nachname', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HauptZiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziel', models.CharField(max_length=256, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.fitnessouser')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=32, null=True)),
                ('nachname', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unterziel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziel', models.CharField(max_length=128, null=True)),
                ('status', models.BooleanField(default=True)),
                ('hauptziel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.hauptziel')),
            ],
        ),
        migrations.AddField(
            model_name='fitnessouser',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.trainer'),
        ),
    ]
